### ISSUE TITLE
Submodule clone fails

### ISSUE THREAD

**Issue by ajweeks** [mkeeter/mpr#1]
When cloning the repository with all submodules, I get the following error:

```
C:\Code\mpr2>git clone --recursive https://github.com/mkeeter/mpr
Cloning into 'mpr'...
remote: Enumerating objects: 2693, done.
remote: Counting objects: 100% (2693/2693), done.
remote: Compressing objects: 100% (779/779), done.
Rremote: Total 2693 (delta 1923), reused 2678 (delta 1908), pack-reused 0eceiving objects:  99% (2667/2693), 1.48 MiB | 2.94 MiB/s
Receiving objects: 100% (2693/2693), 1.82 MiB | 3.18 MiB/s, done.
Resolving deltas: 100% (1923/1923), done.
Submodule 'libfive' (git@github.com:libfive/libfive) registered for path 'libfive'
Cloning into 'C:/Code/mpr2/mpr/libfive'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:libfive/libfive' into submodule path 'C:/Code/mpr2/mpr/libfive' failed
```

Is the intention to use a git account with a username "git"? Or is there a typical use case I'm unaware of?

Running the following commands on a fork allowed me to pull the submodule without errors:

`git config submodule.libfive.url https://github.com/libfive/libfive`

`git submodule update --recursive --remote`

I would make a PR but this modifies `.git/config` and I'm unsure if/how those sorts of changes can be merged. There also might be another step necessary to push the results to the remote, I'm not sure.

Really nice paper by the way, I'm excited to try out the technique 🙂

**Comment by mkeeter** [comment]
Good catch: using `git@github.com:libfive/libfive` only works if you have an SSH key associated with your account.

I switched to the HTTPS path like you suggested, so this should be fixed in 65194066afabc678b270292a10abe0fda02dc098.
